main: yy.gourlitburo.sorata.Main
name: Sorata
version: 0.1.1
api-version: 1.14
author: Zack Guard
description: A manager for owned tameables.
commands:
  sorata:
    description: Use Sorata.
    usage: "Usage: /sorata (list-all | list-type <type> | tp-all | tp-type <type>)"
    permission: sorata.use
permissions:
  sorata.use:
    default: op
