main: yy.gourlitburo.sorata.Main
name: Sorata
version: 0.0.0
api-version: 1.14
author: Zack Guard
# description:
commands:
  sorata:
    description: Use Sorata.
    usage: "Usage: /sorata (list-all | tp-all | tp-all-type <type>)"
    permission: sorata.use
permissions:
  sorata.use:
    default: op
